name: Meson Lint, Build, Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
    - uses: extractions/setup-just@v3
    - name: Install Python Dependencies
      run: pip install meson ninja
    - name: Lint
      run: just lint
    - name: Build
      run: just build
    - name: Test
      run: just test

